package tw.com.ezlifetech.ezReco.model;
// Generated 2019/9/27 �W�� 11:40:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;
import tw.com.ezlifetech.ezReco.util.StringUtil;

/**
 * ArClass generated by hbm2java
 */
@Entity
@Table(name = "ar_class")
public class ArClass extends GenericEntity<String> {

	private String id;
	private String className;
	private String status;
	private String sortIndex;
	private String classParentId;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public ArClass() {
	}

	public ArClass(String id, String className, String status, String createUser, Date createTime) {
		this.id = id;
		this.className = className;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public ArClass(String id, String className, String status, String sortIndex, String classParentId,
			String createUser, Date createTime, String updateUser, Date updateTime, String systemMemo) {
		this.id = id;
		this.className = className;
		this.status = status;
		this.sortIndex = sortIndex;
		this.classParentId = classParentId;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "class_serno", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = StringUtil.getParameter(id);
	}

	@Column(name = "class_name", nullable = false, length = 20)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "sort_index", length = 3)
	public String getSortIndex() {
		return this.sortIndex;
	}

	public void setSortIndex(String sortIndex) {
		this.sortIndex = sortIndex;
	}

	@Column(name = "class_parent_id", length = 20)
	public String getClassParentId() {
		return this.classParentId;
	}

	public void setClassParentId(String classParentId) {
		this.classParentId = classParentId;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
