package tw.com.ezlifetech.ezReco.model;
// Generated 2018/10/17 �U�� 10:36:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * VrItemDl generated by hbm2java
 */
@Entity
@Table(name = "ar_item_dl", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "target_id"))
public class ArItemDl extends GenericEntity<String> {

	private String id;
	private String htId;
	private String targetId;
	private String imgPath;
	private String isMainImg;
	private String status;
	private String action;
	private String var;
	private String metaData;
	private String rating;
	private String uploadPath;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public ArItemDl() {
	}

	public ArItemDl(String id, String htId, String targetId, String imgPath, String isMainImg, String status,
			String action, String var, String createUser, Date createTime) {
		this.id = id;
		this.htId = htId;
		this.targetId = targetId;
		this.imgPath = imgPath;
		this.isMainImg = isMainImg;
		this.status = status;
		this.action = action;
		this.var = var;
		this.createUser = createUser;
		this.createTime = createTime;
	}


	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ht_id", nullable = false, length = 30)
	public String getHtId() {
		return this.htId;
	}

	public void setHtId(String htId) {
		this.htId = htId;
	}

	@Column(name = "target_id", unique = true, nullable = false, length = 200)
	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	@Column(name = "img_path", nullable = false, length = 400)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "is_main_img", nullable = false, length = 5)
	public String getIsMainImg() {
		return this.isMainImg;
	}

	public void setIsMainImg(String isMainImg) {
		this.isMainImg = isMainImg;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "action", nullable = false, length = 30)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "var", nullable = false, length = 500)
	public String getVar() {
		return this.var;
	}

	public void setVar(String var) {
		this.var = var;
	}
	
	@Column(name = "meta_data", length = 200)
	public String getMetaData() {
		return this.metaData;
	}

	public void setMetaData(String metaData) {
		this.metaData = metaData;
	}

	@Column(name = "rating", length = 20)
	public String getRating() {
		return rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}
	
	@Column(name = "upload_path", length = 400)
	public String getUploadPath() {
		return uploadPath;
	}

	public void setUploadPath(String uploadPath) {
		this.uploadPath = uploadPath;
	}
	
	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	

	

}
