package tw.com.ezlifetech.ezReco.model;
// Generated 2018/9/23 �U�� 09:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * SysparamDl generated by hbm2java
 */
@Entity
@Table(name = "sysparam_dl", schema = "public")
public class BasicSysparamDl extends GenericEntity<String> {

	private String id;
	private String htId;
	private String paramCode;
	private String param1;
	private String param2;
	private String param3;
	private String param4;
	private String param5;
	private String systemMemo;
	private String isDelete;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;

	public BasicSysparamDl() {
	}

	public BasicSysparamDl(String id, String htId, String paramCode, String isDelete, String createUser, Date createTime) {
		this.id = id;
		this.htId = htId;
		this.paramCode = paramCode;
		this.isDelete = isDelete;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ht_id", nullable = false, length = 30)
	public String getHtId() {
		return this.htId;
	}

	public void setHtId(String htId) {
		this.htId = htId;
	}

	@Column(name = "param_code", nullable = false, length = 50)
	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	@Column(name = "param1", length = 4000)
	public String getParam1() {
		return this.param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	@Column(name = "param2", length = 4000)
	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

	@Column(name = "param3", length = 4000)
	public String getParam3() {
		return this.param3;
	}

	public void setParam3(String param3) {
		this.param3 = param3;
	}

	@Column(name = "param4", length = 4000)
	public String getParam4() {
		return this.param4;
	}

	public void setParam4(String param4) {
		this.param4 = param4;
	}

	@Column(name = "param5", length = 4000)
	public String getParam5() {
		return this.param5;
	}

	public void setParam5(String param5) {
		this.param5 = param5;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	@Column(name = "is_delete", nullable = false, length = 5)
	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
