package tw.com.ezlifetech.ezReco.model;
// Generated 2018/9/23 �U�� 09:37:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * SysparamHt generated by hbm2java
 */
@Entity
@Table(name = "sysparam_ht", schema = "public")
public class BasicSysparamHt extends GenericEntity<String> {

	private String id;
	private String paramCode;
	private String paramName;
	private String paramContent;
	private String name1;
	private String name2;
	private String name3;
	private String name4;
	private String name5;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public BasicSysparamHt() {
	}

	public BasicSysparamHt(String id, String paramCode, String paramName, String paramContent, String createUser,
			Date createTime) {
		this.id = id;
		this.paramCode = paramCode;
		this.paramName = paramName;
		this.paramContent = paramContent;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "param_code", nullable = false, length = 50)
	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	@Column(name = "param_name", nullable = false, length = 200)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	@Column(name = "param_content", nullable = false, length = 400)
	public String getParamContent() {
		return this.paramContent;
	}

	public void setParamContent(String paramContent) {
		this.paramContent = paramContent;
	}

	@Column(name = "name1", length = 4000)
	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	@Column(name = "name2", length = 4000)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	@Column(name = "name3", length = 4000)
	public String getName3() {
		return this.name3;
	}

	public void setName3(String name3) {
		this.name3 = name3;
	}

	@Column(name = "name4", length = 4000)
	public String getName4() {
		return this.name4;
	}

	public void setName4(String name4) {
		this.name4 = name4;
	}

	@Column(name = "name5", length = 4000)
	public String getName5() {
		return this.name5;
	}

	public void setName5(String name5) {
		this.name5 = name5;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
