package tw.com.ezlifetech.ezReco.model;
// Generated 2019/6/22 下午 10:43:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * ComProfHt generated by hbm2java
 */
@Entity
@Table(name = "com_prof_ht", schema = "public")
public class ComProfHt extends GenericEntity<String> {

	private String id;
	private String comCode;
	private String comAbbr;
	private String comName;
	private String comType;
	private String ban;
	private String comouw;
	private String comBank;
	private String comBkNo;
	private String comComn;
	private String comZpn;
	private String comAdr;
	private String comTel;
	private String comFax;
	private Character comsutp;
	private Integer comltno;
	private String comEmail;
	private Character comZtp;
	private String comCzp;
	private String comCadr;
	private String comzpno;
	private String comCtel;
	private String comCfax;
	private Character comskd;
	private Character comNoneTax;
	private String comFill;
	private String startDate;
	private String endDate;
	private String rentMark;
	private Date aliveSdate;
	private Date aliveEdate;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public ComProfHt() {
	}

	public ComProfHt(String id, String comName, String ban, String createUser, Date createTime) {
		this.id = id;
		this.comName = comName;
		this.ban = ban;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public ComProfHt(String id, String comAbbr, String comName, String comType, String ban, String comouw,
			String comBank, String comBkNo, String comComn, String comZpn, String comAdr, String comTel, String comFax,
			Character comsutp, Integer comltno, String comEmail, Character comZtp, String comCzp, String comCadr,
			String comzpno, String comCtel, String comCfax, Character comskd, Character comNoneTax, String comFill,
			String startDate, String endDate, String rentMark, Date aliveSdate, Date aliveEdate, String createUser,
			Date createTime, String updateUser, Date updateTime, String systemMemo) {
		this.id = id;
		this.comAbbr = comAbbr;
		this.comName = comName;
		this.comType = comType;
		this.ban = ban;
		this.comouw = comouw;
		this.comBank = comBank;
		this.comBkNo = comBkNo;
		this.comComn = comComn;
		this.comZpn = comZpn;
		this.comAdr = comAdr;
		this.comTel = comTel;
		this.comFax = comFax;
		this.comsutp = comsutp;
		this.comltno = comltno;
		this.comEmail = comEmail;
		this.comZtp = comZtp;
		this.comCzp = comCzp;
		this.comCadr = comCadr;
		this.comzpno = comzpno;
		this.comCtel = comCtel;
		this.comCfax = comCfax;
		this.comskd = comskd;
		this.comNoneTax = comNoneTax;
		this.comFill = comFill;
		this.startDate = startDate;
		this.endDate = endDate;
		this.rentMark = rentMark;
		this.aliveSdate = aliveSdate;
		this.aliveEdate = aliveEdate;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "com_id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "com_code", length = 30)
	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}
	
	@Column(name = "com_abbr", length = 40)
	public String getComAbbr() {
		return this.comAbbr;
	}

	public void setComAbbr(String comAbbr) {
		this.comAbbr = comAbbr;
	}

	@Column(name = "com_name", nullable = false, length = 120)
	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@Column(name = "com_type", length = 5)
	public String getComType() {
		return this.comType;
	}

	public void setComType(String comType) {
		this.comType = comType;
	}

	@Column(name = "ban", nullable = false, length = 20)
	public String getBan() {
		return this.ban;
	}

	public void setBan(String ban) {
		this.ban = ban;
	}

	@Column(name = "comouw", length = 30)
	public String getComouw() {
		return this.comouw;
	}

	public void setComouw(String comouw) {
		this.comouw = comouw;
	}

	@Column(name = "com_bank", length = 20)
	public String getComBank() {
		return this.comBank;
	}

	public void setComBank(String comBank) {
		this.comBank = comBank;
	}

	@Column(name = "com_bk_no", length = 30)
	public String getComBkNo() {
		return this.comBkNo;
	}

	public void setComBkNo(String comBkNo) {
		this.comBkNo = comBkNo;
	}

	@Column(name = "com_comn", length = 30)
	public String getComComn() {
		return this.comComn;
	}

	public void setComComn(String comComn) {
		this.comComn = comComn;
	}

	@Column(name = "com_zpn", length = 10)
	public String getComZpn() {
		return this.comZpn;
	}

	public void setComZpn(String comZpn) {
		this.comZpn = comZpn;
	}

	@Column(name = "com_adr", length = 200)
	public String getComAdr() {
		return this.comAdr;
	}

	public void setComAdr(String comAdr) {
		this.comAdr = comAdr;
	}

	@Column(name = "com_tel", length = 20)
	public String getComTel() {
		return this.comTel;
	}

	public void setComTel(String comTel) {
		this.comTel = comTel;
	}

	@Column(name = "com_fax", length = 20)
	public String getComFax() {
		return this.comFax;
	}

	public void setComFax(String comFax) {
		this.comFax = comFax;
	}

	@Column(name = "comsutp", length = 1)
	public Character getComsutp() {
		return this.comsutp;
	}

	public void setComsutp(Character comsutp) {
		this.comsutp = comsutp;
	}

	@Column(name = "comltno", precision = 6, scale = 0)
	public Integer getComltno() {
		return this.comltno;
	}

	public void setComltno(Integer comltno) {
		this.comltno = comltno;
	}

	@Column(name = "com_email", length = 200)
	public String getComEmail() {
		return this.comEmail;
	}

	public void setComEmail(String comEmail) {
		this.comEmail = comEmail;
	}

	@Column(name = "com_ztp", length = 1)
	public Character getComZtp() {
		return this.comZtp;
	}

	public void setComZtp(Character comZtp) {
		this.comZtp = comZtp;
	}

	@Column(name = "com_czp", length = 10)
	public String getComCzp() {
		return this.comCzp;
	}

	public void setComCzp(String comCzp) {
		this.comCzp = comCzp;
	}

	@Column(name = "com_cadr", length = 200)
	public String getComCadr() {
		return this.comCadr;
	}

	public void setComCadr(String comCadr) {
		this.comCadr = comCadr;
	}

	@Column(name = "comzpno", length = 20)
	public String getComzpno() {
		return this.comzpno;
	}

	public void setComzpno(String comzpno) {
		this.comzpno = comzpno;
	}

	@Column(name = "com_ctel", length = 20)
	public String getComCtel() {
		return this.comCtel;
	}

	public void setComCtel(String comCtel) {
		this.comCtel = comCtel;
	}

	@Column(name = "com_cfax", length = 20)
	public String getComCfax() {
		return this.comCfax;
	}

	public void setComCfax(String comCfax) {
		this.comCfax = comCfax;
	}

	@Column(name = "comskd", length = 1)
	public Character getComskd() {
		return this.comskd;
	}

	public void setComskd(Character comskd) {
		this.comskd = comskd;
	}

	@Column(name = "com_none_tax", length = 1)
	public Character getComNoneTax() {
		return this.comNoneTax;
	}

	public void setComNoneTax(Character comNoneTax) {
		this.comNoneTax = comNoneTax;
	}

	@Column(name = "com_fill", length = 50)
	public String getComFill() {
		return this.comFill;
	}

	public void setComFill(String comFill) {
		this.comFill = comFill;
	}

	@Column(name = "start_date", length = 20)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", length = 20)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "rent_mark", length = 2)
	public String getRentMark() {
		return this.rentMark;
	}

	public void setRentMark(String rentMark) {
		this.rentMark = rentMark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alive_sdate", length = 29)
	public Date getAliveSdate() {
		return this.aliveSdate;
	}

	public void setAliveSdate(Date aliveSdate) {
		this.aliveSdate = aliveSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "alive_edate", length = 29)
	public Date getAliveEdate() {
		return this.aliveEdate;
	}

	public void setAliveEdate(Date aliveEdate) {
		this.aliveEdate = aliveEdate;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	

}
