package tw.com.ezlifetech.ezReco.model;
// Generated 2019/6/22 �U�� 10:03:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * DispatcherProfile generated by hbm2java
 */
@Entity
@Table(name = "dispatcher_profile", schema = "public")
public class DispatcherProfile extends GenericEntity<String> {

	private String id;
	private String compId;
	private String whId;
	private String idNumber;
	private String userId;
	private String name;
	private Date birthday;
	private String sex;
	private String addr;
	private String timingOrOiece;
	private String phone;
	private String education;
	private String stackerLicense;
	private Date stackerLicenseLimitDate;
	private String electricTrailer;
	private String laborPortection;
	private String healthInsurance;
	private String resPermitNumber;
	private Date resPermitLimitDate;
	private String workPermitNumber;
	private Date workPermitNumberLimitDate;
	private String studentPemitNumber;
	private Date studentPemitNumberLimitDate;
	private String photoPath;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public DispatcherProfile() {
	}

	public DispatcherProfile(String id, String createUser, Date createTime) {
		this.id = id;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public DispatcherProfile(String id, String compId, String whId, String idNumber, String userId, String name,
			Date birthday, String sex, String addr, String timingOrOiece, String phone, String education,
			String stackerLicense, Date stackerLicenseLimitDate, String electricTrailer, String laborPortection,
			String healthInsurance, String resPermitNumber, Date resPermitLimitDate, String workPermitNumber,
			Date workPermitNumberLimitDate, String studentPemitNumber, Date studentPemitNumberLimitDate,
			String photoPath, String createUser, Date createTime, String updateUser, Date updateTime,
			String systemMemo) {
		this.id = id;
		this.compId = compId;
		this.whId = whId;
		this.idNumber = idNumber;
		this.userId = userId;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.addr = addr;
		this.timingOrOiece = timingOrOiece;
		this.phone = phone;
		this.education = education;
		this.stackerLicense = stackerLicense;
		this.stackerLicenseLimitDate = stackerLicenseLimitDate;
		this.electricTrailer = electricTrailer;
		this.laborPortection = laborPortection;
		this.healthInsurance = healthInsurance;
		this.resPermitNumber = resPermitNumber;
		this.resPermitLimitDate = resPermitLimitDate;
		this.workPermitNumber = workPermitNumber;
		this.workPermitNumberLimitDate = workPermitNumberLimitDate;
		this.studentPemitNumber = studentPemitNumber;
		this.studentPemitNumberLimitDate = studentPemitNumberLimitDate;
		this.photoPath = photoPath;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "comp_id", length = 30)
	public String getCompId() {
		return this.compId;
	}

	public void setCompId(String compId) {
		this.compId = compId;
	}

	@Column(name = "wh_id", length = 30)
	public String getWhId() {
		return this.whId;
	}

	public void setWhId(String whId) {
		this.whId = whId;
	}

	@Column(name = "id_number", length = 30)
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "user_id", length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 29)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "sex", length = 5)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "addr", length = 1000)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "timing_or_oiece", length = 5)
	public String getTimingOrOiece() {
		return this.timingOrOiece;
	}

	public void setTimingOrOiece(String timingOrOiece) {
		this.timingOrOiece = timingOrOiece;
	}

	@Column(name = "phone", length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "education", length = 50)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "stacker_license", length = 50)
	public String getStackerLicense() {
		return this.stackerLicense;
	}

	public void setStackerLicense(String stackerLicense) {
		this.stackerLicense = stackerLicense;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "stacker_license_limit_date", length = 29)
	public Date getStackerLicenseLimitDate() {
		return this.stackerLicenseLimitDate;
	}

	public void setStackerLicenseLimitDate(Date stackerLicenseLimitDate) {
		this.stackerLicenseLimitDate = stackerLicenseLimitDate;
	}

	@Column(name = "electric_trailer", length = 50)
	public String getElectricTrailer() {
		return this.electricTrailer;
	}

	public void setElectricTrailer(String electricTrailer) {
		this.electricTrailer = electricTrailer;
	}

	@Column(name = "labor_portection", length = 30)
	public String getLaborPortection() {
		return this.laborPortection;
	}

	public void setLaborPortection(String laborPortection) {
		this.laborPortection = laborPortection;
	}

	@Column(name = "health_insurance", length = 30)
	public String getHealthInsurance() {
		return this.healthInsurance;
	}

	public void setHealthInsurance(String healthInsurance) {
		this.healthInsurance = healthInsurance;
	}

	@Column(name = "res_permit_number", length = 50)
	public String getResPermitNumber() {
		return this.resPermitNumber;
	}

	public void setResPermitNumber(String resPermitNumber) {
		this.resPermitNumber = resPermitNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "res_permit_limit_date", length = 29)
	public Date getResPermitLimitDate() {
		return this.resPermitLimitDate;
	}

	public void setResPermitLimitDate(Date resPermitLimitDate) {
		this.resPermitLimitDate = resPermitLimitDate;
	}

	@Column(name = "work_permit_number", length = 50)
	public String getWorkPermitNumber() {
		return this.workPermitNumber;
	}

	public void setWorkPermitNumber(String workPermitNumber) {
		this.workPermitNumber = workPermitNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "work_permit_number_limit_date", length = 29)
	public Date getWorkPermitNumberLimitDate() {
		return this.workPermitNumberLimitDate;
	}

	public void setWorkPermitNumberLimitDate(Date workPermitNumberLimitDate) {
		this.workPermitNumberLimitDate = workPermitNumberLimitDate;
	}

	@Column(name = "student_pemit_number", length = 50)
	public String getStudentPemitNumber() {
		return this.studentPemitNumber;
	}

	public void setStudentPemitNumber(String studentPemitNumber) {
		this.studentPemitNumber = studentPemitNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "student_pemit_number_limit_date", length = 29)
	public Date getStudentPemitNumberLimitDate() {
		return this.studentPemitNumberLimitDate;
	}

	public void setStudentPemitNumberLimitDate(Date studentPemitNumberLimitDate) {
		this.studentPemitNumberLimitDate = studentPemitNumberLimitDate;
	}

	@Column(name = "photo_path", length = 200)
	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
