package tw.com.ezlifetech.ezReco.model;
// Generated 2019/6/16 �U�� 11:06:54 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * GoHt generated by hbm2java
 */
@Entity
@Table(name = "go_ht", schema = "public")
public class GoHt extends GenericEntity<String> {

	private String id;
	private String goSysType;
	private String goStatus;
	private String userId;
	private String userName;
	private String logisticId;
	private String comId;
	private String whId;
	private String wcsId;
	private String contractType;
	private Date SGoSystime;
	private Date SGoTime;
	private String SPlace;
	private String SGps;
	private String SAddr;
	private String SCreateUser;
	private Date SCreateTime;
	private Date EGoSystime;
	private Date EGoTime;
	private String EPlace;
	private String EGps;
	private String EAddr;
	private String ECreateUser;
	private Date ECreateTime;
	private String goDis;
	private String goTime;
	private String goSalary;
	private String goGeneralHr;
	private String goGeneralSal;
	private String goOvtHr;
	private String goOvtSal;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public GoHt() {
	}

	public GoHt(String id, String goSysType, String goStatus, String userId, String updateUser, Date updateTime) {
		this.id = id;
		this.goSysType = goSysType;
		this.goStatus = goStatus;
		this.userId = userId;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	@Id

	@Column(name = "go_id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "go_sys_type", nullable = false, length = 10)
	public String getGoSysType() {
		return this.goSysType;
	}

	public void setGoSysType(String goSysType) {
		this.goSysType = goSysType;
	}

	@Column(name = "go_status", nullable = false, length = 10)
	public String getGoStatus() {
		return this.goStatus;
	}

	public void setGoStatus(String goStatus) {
		this.goStatus = goStatus;
	}

	@Column(name = "user_id", nullable = false, length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "logistic_Id", length = 30)
	public String getLogisticId() {
		return logisticId;
	}

	public void setLogisticId(String logisticId) {
		this.logisticId = logisticId;
	}

	@Column(name = "com_id", length = 30)
	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "wh_id", length = 30)
	public String getWhId() {
		return this.whId;
	}

	public void setWhId(String whId) {
		this.whId = whId;
	}
	
	@Column(name = "wcs_id", length = 30)
	public String getWcsId() {
		return wcsId;
	}

	public void setWcsId(String wcsId) {
		this.wcsId = wcsId;
	}
	
	@Column(name = "contract_type", length = 30)
	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "s_go_systime", length = 29)
	public Date getSGoSystime() {
		return this.SGoSystime;
	}

	public void setSGoSystime(Date SGoSystime) {
		this.SGoSystime = SGoSystime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "s_go_time", length = 29)
	public Date getSGoTime() {
		return this.SGoTime;
	}

	public void setSGoTime(Date SGoTime) {
		this.SGoTime = SGoTime;
	}

	@Column(name = "s_place", length = 100)
	public String getSPlace() {
		return this.SPlace;
	}

	public void setSPlace(String SPlace) {
		this.SPlace = SPlace;
	}

	@Column(name = "s_gps", length = 30)
	public String getSGps() {
		return this.SGps;
	}

	public void setSGps(String SGps) {
		this.SGps = SGps;
	}

	@Column(name = "s_addr", length = 500)
	public String getSAddr() {
		return this.SAddr;
	}

	public void setSAddr(String SAddr) {
		this.SAddr = SAddr;
	}

	@Column(name = "s_create_user", length = 30)
	public String getSCreateUser() {
		return this.SCreateUser;
	}

	public void setSCreateUser(String SCreateUser) {
		this.SCreateUser = SCreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "s_create_time", length = 29)
	public Date getSCreateTime() {
		return this.SCreateTime;
	}

	public void setSCreateTime(Date SCreateTime) {
		this.SCreateTime = SCreateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "e_go_systime", length = 29)
	public Date getEGoSystime() {
		return this.EGoSystime;
	}

	public void setEGoSystime(Date EGoSystime) {
		this.EGoSystime = EGoSystime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "e_go_time", length = 29)
	public Date getEGoTime() {
		return this.EGoTime;
	}

	public void setEGoTime(Date EGoTime) {
		this.EGoTime = EGoTime;
	}

	@Column(name = "e_place", length = 100)
	public String getEPlace() {
		return this.EPlace;
	}

	public void setEPlace(String EPlace) {
		this.EPlace = EPlace;
	}

	@Column(name = "e_gps", length = 30)
	public String getEGps() {
		return this.EGps;
	}

	public void setEGps(String EGps) {
		this.EGps = EGps;
	}

	@Column(name = "e_addr", length = 500)
	public String getEAddr() {
		return this.EAddr;
	}

	public void setEAddr(String EAddr) {
		this.EAddr = EAddr;
	}

	@Column(name = "e_create_user", length = 30)
	public String getECreateUser() {
		return this.ECreateUser;
	}

	public void setECreateUser(String ECreateUser) {
		this.ECreateUser = ECreateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "e_create_time", length = 29)
	public Date getECreateTime() {
		return this.ECreateTime;
	}

	public void setECreateTime(Date ECreateTime) {
		this.ECreateTime = ECreateTime;
	}

	@Column(name = "go_dis", length = 10)
	public String getGoDis() {
		return this.goDis;
	}

	public void setGoDis(String goDis) {
		this.goDis = goDis;
	}

//	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "go_time", length = 30)
	public String getGoTime() {
		return this.goTime;
	}

	public void setGoTime(String goTime) {
		this.goTime = goTime;
	}

	@Column(name = "go_salary", length = 30)

	public String getGoSalary() {
		return goSalary;
	}

	public void setGoSalary(String goSalary) {
		this.goSalary = goSalary;
	}
	
	@Column(name = "go_general_hr", length = 30)
	public String getGoGeneralHr() {
		return this.goGeneralHr;
	}

	public void setGoGeneralHr(String goGeneralHr) {
		this.goGeneralHr = goGeneralHr;
	}

	@Column(name = "go_general_sal", length = 30)
	public String getGoGeneralSal() {
		return this.goGeneralSal;
	}

	public void setGoGeneralSal(String goGeneralSal) {
		this.goGeneralSal = goGeneralSal;
	}

	@Column(name = "go_ovt_hr", length = 30)
	public String getGoOvtHr() {
		return this.goOvtHr;
	}

	public void setGoOvtHr(String goOvtHr) {
		this.goOvtHr = goOvtHr;
	}

	@Column(name = "go_ovt_sal", length = 30)
	public String getGoOvtSal() {
		return this.goOvtSal;
	}

	public void setGoOvtSal(String goOvtSal) {
		this.goOvtSal = goOvtSal;
	}

	@Column(name = "update_user", nullable = false, length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
