package tw.com.ezlifetech.ezReco.model;
// Generated 2018/7/30 �U�� 10:25:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;
import tw.com.ezlifetech.ezReco.util.StringUtil;

/**
 * LoggSystem generated by hbm2java
 */
@Entity
@Table(name = "logg_system", schema = "public")
public class LoggSystem extends GenericEntity<String> {


	private static final long serialVersionUID = 1L;
	private String id;
	private String logType;
	private String functionCode;
	private String actionCode;
	private String userSessionId;
	private String userIp;
	private String userId;
	private String logContent;
	private String argumentVal;
	private String logMemo;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;
	private String systemMemo;

	public LoggSystem() {
	}

	public LoggSystem( String logType, String functionCode, String actionCode) {
		
		this.logType = logType;
		this.functionCode = functionCode;
		this.actionCode = actionCode;
	}

	

	@Id
	@Column(name = "sequenceno", unique = true, nullable = false)
	public String getId() {
		// TODO Auto-generated method stub
		return id;
	}

	
	public void setId(String id) {
		this.id = StringUtil.getParameter(id);
		
	}
	

	@Column(name = "log_type", nullable = false, length = 20)
	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	@Column(name = "function_code", nullable = false, length = 50)
	public String getFunctionCode() {
		return this.functionCode;
	}

	public void setFunctionCode(String functionCode) {
		this.functionCode = functionCode;
	}

	@Column(name = "action_code", nullable = false, length = 50)
	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	@Column(name = "user_session_id", length = 200)
	public String getUserSessionId() {
		return this.userSessionId;
	}

	public void setUserSessionId(String userSessionId) {
		this.userSessionId = userSessionId;
	}

	@Column(name = "user_ip", length = 50)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "user_id", length = 30)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "log_content", length = 1000)
	public String getLogContent() {
		return this.logContent;
	}

	public void setLogContent(String logContent) {
		this.logContent = logContent;
	}

	@Column(name = "argument_val", length = 1000)
	public String getArgumentVal() {
		return this.argumentVal;
	}

	public void setArgumentVal(String argumentVal) {
		this.argumentVal = argumentVal;
	}

	@Column(name = "log_memo", length = 1000)
	public String getLogMemo() {
		return this.logMemo;
	}

	public void setLogMemo(String logMemo) {
		this.logMemo = logMemo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "create_user", length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	

}
