package tw.com.ezlifetech.ezReco.model;
// Generated 2018/8/4 �U�� 04:17:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;
import tw.com.ezlifetech.ezReco.util.StringUtil;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
public class Product extends GenericEntity<String> {

	private String id;
	private String proCode;
	private String prodLang;
	private String proName;
	private String proNameEn;
	private String proSpec;
	private String proSpecEn;
	private String proSellPrice;
	private String proInPrice;
	private String status;
	private String proHtml;
	private String proParamHtml;
	private String proHtmlEn;
	private String proParamHtmlEn;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public Product() {
	}

	public Product(String id,String prodLang, String proName, String proSpec, String proSellPrice, String status) {
		this.id = id;
		this.prodLang = prodLang;
		this.proName = proName;
		this.proSpec = proSpec;
		this.proSellPrice = proSellPrice;
		this.status = status;
	}


	@Id

	@Column(name = "pro_no", unique = true, nullable = false, length = 20)
	public String getId() {
		// TODO Auto-generated method stub
		return id;
	}

	
	public void setId(String id) {
		this.id = StringUtil.getParameter(id);
		
	}
	
	@Column(name = "pro_code", nullable = false, length = 50)
	public String getProCode() {
		return proCode;
	}

	public void setProCode(String proCode) {
		this.proCode = proCode;
	}

	@Column(name = "prod_lang", nullable = true, length = 200)
	public String getProdLang() {
		return this.prodLang;
	}

	public void setProdLang(String prodLang) {
		this.prodLang = prodLang;
	}
	
	@Column(name = "pro_name", nullable = false, length = 200)
	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}
	
	@Column(name = "pro_name_en", nullable = false, length = 200)
	public String getProNameEn() {
		return this.proNameEn;
	}

	public void setProNameEn(String proNameEn) {
		this.proNameEn = proNameEn;
	}

	@Column(name = "pro_spec", nullable = false, length = 300)
	public String getProSpec() {
		return this.proSpec;
	}

	public void setProSpec(String proSpec) {
		this.proSpec = proSpec;
	}
	
	@Column(name = "pro_spec_en", nullable = false, length = 300)
	public String getProSpecEn() {
		return this.proSpecEn;
	}

	public void setProSpecEn(String proSpecEn) {
		this.proSpecEn = proSpecEn;
	}

	@Column(name = "pro_sell_price", nullable = false, length = 20)
	public String getProSellPrice() {
		return this.proSellPrice;
	}

	public void setProSellPrice(String proSellPrice) {
		this.proSellPrice = proSellPrice;
	}

	@Column(name = "pro_in_price", length = 20)
	public String getProInPrice() {
		return this.proInPrice;
	}

	public void setProInPrice(String proInPrice) {
		this.proInPrice = proInPrice;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "pro_html")
	public String getProHtml() {
		return this.proHtml;
	}

	public void setProHtml(String proHtml) {
		this.proHtml = proHtml;
	}
	
	@Column(name = "pro_param_html")
	public String getProParamHtml() {
		return proParamHtml;
	}

	public void setProParamHtml(String proParamHtml) {
		this.proParamHtml = proParamHtml;
	}

	
	
	@Column(name = "pro_html_en")
	public String getProHtmlEn() {
		return this.proHtmlEn;
	}

	public void setProHtmlEn(String proHtmlEn) {
		this.proHtmlEn = proHtmlEn;
	}
	
	@Column(name = "pro_param_html_en")
	public String getProParamHtmlEn() {
		return proParamHtmlEn;
	}

	public void setProParamHtmlEn(String proParamHtmlEn) {
		this.proParamHtmlEn = proParamHtmlEn;
	}

	@Column(name = "create_user", length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	

	

}
