package tw.com.ezlifetech.ezReco.model;
// Generated 2018/9/9 �W�� 02:30:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * ProductSale generated by hbm2java
 */
@Entity
@Table(name = "product_sale", schema = "public")
public class ProductSale extends GenericEntity<String> {

	private String id;
	private String saleName;
	private String saleMode;
	private Date saleSdate;
	private Date saleEdate;
	private String saleTargetType;
	private String parameter1;
	private String parameter2;
	private String parameter3;
	private String parameter4;
	private String parameter5;
	private String parameter6;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public ProductSale() {
	}

	public ProductSale(String id, String saleName, String saleMode, Date saleSdate, Date saleEdate,
			String saleTargetType, String createUser, Date createTime) {
		this.id = id;
		this.saleName = saleName;
		this.saleMode = saleMode;
		this.saleSdate = saleSdate;
		this.saleEdate = saleEdate;
		this.saleTargetType = saleTargetType;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public ProductSale(String id, String saleName, String saleMode, Date saleSdate, Date saleEdate,
			String saleTargetType, String parameter1, String parameter2, String parameter3, String parameter4,
			String parameter5, String parameter6, String createUser, Date createTime, String updateUser,
			Date updateTime, String systemMemo) {
		this.id = id;
		this.saleName = saleName;
		this.saleMode = saleMode;
		this.saleSdate = saleSdate;
		this.saleEdate = saleEdate;
		this.saleTargetType = saleTargetType;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.parameter6 = parameter6;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "sale_name", nullable = false, length = 100)
	public String getSaleName() {
		return this.saleName;
	}

	public void setSaleName(String saleName) {
		this.saleName = saleName;
	}

	@Column(name = "sale_mode", nullable = false, length = 30)
	public String getSaleMode() {
		return this.saleMode;
	}

	public void setSaleMode(String saleMode) {
		this.saleMode = saleMode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sale_sdate", nullable = false, length = 29)
	public Date getSaleSdate() {
		return this.saleSdate;
	}

	public void setSaleSdate(Date saleSdate) {
		this.saleSdate = saleSdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sale_edate", nullable = false, length = 29)
	public Date getSaleEdate() {
		return this.saleEdate;
	}

	public void setSaleEdate(Date saleEdate) {
		this.saleEdate = saleEdate;
	}

	@Column(name = "sale_target_type", nullable = false, length = 30)
	public String getSaleTargetType() {
		return this.saleTargetType;
	}

	public void setSaleTargetType(String saleTargetType) {
		this.saleTargetType = saleTargetType;
	}

	@Column(name = "parameter1", length = 100)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", length = 100)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", length = 100)
	public String getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(String parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", length = 100)
	public String getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(String parameter4) {
		this.parameter4 = parameter4;
	}

	@Column(name = "parameter5", length = 100)
	public String getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(String parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "parameter6", length = 100)
	public String getParameter6() {
		return this.parameter6;
	}

	public void setParameter6(String parameter6) {
		this.parameter6 = parameter6;
	}

	@Column(name = "create_user", nullable = false, length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
