package tw.com.ezlifetech.ezReco.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * QuestionAnswerList generated by hbm2java
 */
@Entity
@Table(name = "question_answer_list", schema = "public")
public class QuestionAnswerList extends GenericEntity<String> {

	private String id;
	private String questType;
	private String status;
	private String refId;
	private String questName;
	private String questMail;
	private String questPhone;
	private String questTitle;
	private String questContent;
	private String isAns;
	private Date ansTime;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public QuestionAnswerList() {
	}

	public QuestionAnswerList(String id, String questType, String status, String createUser, Date createTime) {
		this.id = id;
		this.questType = questType;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "quest_type", nullable = false, length = 30)
	public String getQuestType() {
		return this.questType;
	}

	public void setQuestType(String questType) {
		this.questType = questType;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ref_id", length = 30)
	public String getRefId() {
		return this.refId;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	@Column(name = "quest_name", length = 100)
	public String getQuestName() {
		return this.questName;
	}

	public void setQuestName(String questName) {
		this.questName = questName;
	}

	@Column(name = "quest_mail", length = 200)
	public String getQuestMail() {
		return this.questMail;
	}

	public void setQuestMail(String questMail) {
		this.questMail = questMail;
	}

	@Column(name = "quest_phone", length = 200)
	public String getQuestPhone() {
		return this.questPhone;
	}

	public void setQuestPhone(String questPhone) {
		this.questPhone = questPhone;
	}

	@Column(name = "quest_title")
	public String getQuestTitle() {
		return this.questTitle;
	}

	public void setQuestTitle(String questTitle) {
		this.questTitle = questTitle;
	}

	@Column(name = "quest_content")
	public String getQuestContent() {
		return this.questContent;
	}

	public void setQuestContent(String questContent) {
		this.questContent = questContent;
	}

	@Column(name = "is_ans", length = 20)
	public String getIsAns() {
		return this.isAns;
	}

	public void setIsAns(String isAns) {
		this.isAns = isAns;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ans_time", length = 29)
	public Date getAnsTime() {
		return this.ansTime;
	}

	public void setAnsTime(Date ansTime) {
		this.ansTime = ansTime;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
