package tw.com.ezlifetech.ezReco.model;
// Generated 2018/7/30 �U�� 10:25:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * RefFunctionRole generated by hbm2java
 */
@Entity
@Table(name = "ref_function_role", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "func_no",
		"role_type", "role_no" }))
public class RefFunctionRole  extends GenericEntity<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String funcNo;
	private String roleType;
	private String roleNo;
	private String authority;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public RefFunctionRole() {
	}

	public RefFunctionRole(String id, String funcNo, String roleType, String roleNo, String authority) {
		this.id = id;
		this.funcNo = funcNo;
		this.roleType = roleType;
		this.roleNo = roleNo;
		this.authority = authority;
	}

	

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "func_no", nullable = false, length = 20)
	public String getFuncNo() {
		return this.funcNo;
	}

	public void setFuncNo(String funcNo) {
		this.funcNo = funcNo;
	}

	@Column(name = "role_type", nullable = false, length = 30)
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	@Column(name = "role_no", nullable = false, length = 30)
	public String getRoleNo() {
		return this.roleNo;
	}

	public void setRoleNo(String roleNo) {
		this.roleNo = roleNo;
	}

	@Column(name = "authority", nullable = false, length = 20)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Column(name = "create_user", length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
