package tw.com.ezlifetech.ezReco.model;
// Generated 2018/7/30 �U�� 10:25:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;
import tw.com.ezlifetech.ezReco.util.StringUtil;

/**
 * HfUser generated by hbm2java
 */
@Entity
@Table(name = "hf_user", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "user_email"))
public class User extends GenericEntity<String>{

	private String id;
	private String userName;
	private String userNameEn;
	private String parentUserId;
	private String comId;
	private String roleType;
	private String roleNo;
	private String userStatus;
	private String ban;
	private String contact;
	private Date userStartDate;
	private Date userCloseDate;
	private String userPwd;
	private Date changePwdTime;
	private Date loginTime;
	private Date loginErrTime;
	private String loginErrTimes;
	private String userAddr;
	private String userCellphone;
	private String userEmail;
	private String userFax;
	private String userTel;
	private String userExt;
	private String pwdKeeper;
	private String pwdKeeperEmail;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public User() {
	}

	public User(String id, String userName, String roleType, String roleNo, String userStatus, Date userStartDate,
			String userPwd, Date changePwdTime, String userEmail) {
		this.id = id;
		this.userName = userName;
		this.roleType = roleType;
		this.roleNo = roleNo;
		this.userStatus = userStatus;
		this.userStartDate = userStartDate;
		this.userPwd = userPwd;
		this.changePwdTime = changePwdTime;
		this.userEmail = userEmail;
	}

	

	@Id

	@Column(name = "user_id", unique = true, nullable = false, length = 60)
	public String getId() {
		// TODO Auto-generated method stub
		return id;
	}

	
	public void setId(String id) {
		this.id = StringUtil.getParameter(id);
		
	}

	@Column(name = "user_name", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_name_en", length = 100)
	public String getUserNameEn() {
		return this.userNameEn;
	}

	public void setUserNameEn(String userNameEn) {
		this.userNameEn = userNameEn;
	}

	@Column(name = "parent_user_id", length = 60)
	public String getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(String parentUserId) {
		this.parentUserId = parentUserId;
	}
	
	@Column(name = "com_id", length = 30)
	public String getComId() {
		return comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	@Column(name = "role_type", nullable = false, length = 30)
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	@Column(name = "role_no", nullable = false, length = 30)
	public String getRoleNo() {
		return this.roleNo;
	}

	public void setRoleNo(String roleNo) {
		this.roleNo = roleNo;
	}

	@Column(name = "user_status", nullable = false, length = 5)
	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}
	
	@Column(name = "ban", length = 15)
	public String getBan() {
		return this.ban;
	}

	public void setBan(String ban) {
		this.ban = ban;
	}

	@Column(name = "contact", length = 30)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_start_date", nullable = false, length = 29)
	public Date getUserStartDate() {
		return this.userStartDate;
	}

	public void setUserStartDate(Date userStartDate) {
		this.userStartDate = userStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_close_date", length = 29)
	public Date getUserCloseDate() {
		return this.userCloseDate;
	}

	public void setUserCloseDate(Date userCloseDate) {
		this.userCloseDate = userCloseDate;
	}

	@Column(name = "user_pwd", nullable = false, length = 500)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_pwd_time", nullable = false, length = 29)
	public Date getChangePwdTime() {
		return this.changePwdTime;
	}

	public void setChangePwdTime(Date changePwdTime) {
		this.changePwdTime = changePwdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 29)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_err_time", length = 29)
	public Date getLoginErrTime() {
		return this.loginErrTime;
	}

	public void setLoginErrTime(Date loginErrTime) {
		this.loginErrTime = loginErrTime;
	}

	@Column(name = "login_err_times", length = 5)
	public String getLoginErrTimes() {
		return this.loginErrTimes;
	}

	public void setLoginErrTimes(String loginErrTimes) {
		this.loginErrTimes = loginErrTimes;
	}

	@Column(name = "user_addr", length = 500)
	public String getUserAddr() {
		return this.userAddr;
	}

	public void setUserAddr(String userAddr) {
		this.userAddr = userAddr;
	}

	@Column(name = "user_cellphone", length = 20)
	public String getUserCellphone() {
		return this.userCellphone;
	}

	public void setUserCellphone(String userCellphone) {
		this.userCellphone = userCellphone;
	}

	@Column(name = "user_email", unique = true, nullable = false, length = 100)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_fax", length = 20)
	public String getUserFax() {
		return this.userFax;
	}

	public void setUserFax(String userFax) {
		this.userFax = userFax;
	}

	@Column(name = "user_tel", length = 20)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}
	
	@Column(name = "user_ext", length = 10)
	public String getUserExt() {
		return this.userExt;
	}

	public void setUserExt(String userExt) {
		this.userExt = userExt;
	}

	@Column(name = "pwd_keeper", length = 30)
	public String getPwdKeeper() {
		return this.pwdKeeper;
	}

	public void setPwdKeeper(String pwdKeeper) {
		this.pwdKeeper = pwdKeeper;
	}

	@Column(name = "pwd_keeper_email", length = 100)
	public String getPwdKeeperEmail() {
		return this.pwdKeeperEmail;
	}

	public void setPwdKeeperEmail(String pwdKeeperEmail) {
		this.pwdKeeperEmail = pwdKeeperEmail;
	}

	@Column(name = "create_user", length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

	

}
