package tw.com.ezlifetech.ezReco.model;
// Generated 2019/6/22 �U�� 10:03:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * WarehouseProfile generated by hbm2java
 */
@Entity
@Table(name = "warehouse_profile", schema = "public")
public class WareHouseProf extends GenericEntity<String> {

	private String id;
	private String whId;
	private String whName;
	private String whComId;
	private String whAddr;
	private String status;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public WareHouseProf() {
	}

	public WareHouseProf(String id, String whId, String status, String createUser, Date createTime) {
		this.id = id;
		this.whId = whId;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public WareHouseProf(String id, String whId, String whName, String whComId, String whAddr,String status, String createUser,
			Date createTime, String updateUser, Date updateTime, String systemMemo) {
		this.id = id;
		this.whId = whId;
		this.whName = whName;
		this.whComId = whComId;
		this.whAddr = whAddr;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "wh_id", nullable = false, length = 30)
	public String getWhId() {
		return this.whId;
	}

	public void setWhId(String whId) {
		this.whId = whId;
	}

	@Column(name = "wh_name", length = 200)
	public String getWhName() {
		return this.whName;
	}

	public void setWhName(String whName) {
		this.whName = whName;
	}

	@Column(name = "wh_com_id", length = 30)
	public String getWhComId() {
		return this.whComId;
	}

	public void setWhComId(String whComId) {
		this.whComId = whComId;
	}

	@Column(name = "wh_addr", length = 1000)
	public String getWhAddr() {
		return this.whAddr;
	}

	public void setWhAddr(String whAddr) {
		this.whAddr = whAddr;
	}
	
	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
