package tw.com.ezlifetech.ezReco.model;
// Generated 2019/11/21 �U�� 09:32:54 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * WebPages generated by hbm2java
 */
@Entity
@Table(name = "web_pages")
public class WebPages extends GenericEntity<String> {

	private String id;
	private String pageName;
	private String pageNameEn;
	private String pageUrl;
	private String pageType;
	private String pageTitle;
	private String pageTitleEn;
	private String pageContent;
	private String pageContentEn;
	private String pageHtml;
	private String pageHtmlEn;
	private String pageSeo;
	private String pageGa;
	private String pageFb;
	private String pageHit;
	private String status;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public WebPages() {
	}

	public WebPages(String id, String status, String createUser, Date createTime) {
		this.id = id;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	public WebPages(String id, String pageName, String pageNameEn, String pageUrl, String pageType, String pageTitle,
			String pageTitleEn, String pageContent, String pageContentEn, String pageHtml, String pageHtmlEn,
			String pageSeo, String pageGa, String pageFb, String pageHit, String status, String createUser,
			Date createTime, String updateUser, Date updateTime, String systemMemo) {
		this.id = id;
		this.pageName = pageName;
		this.pageNameEn = pageNameEn;
		this.pageUrl = pageUrl;
		this.pageType = pageType;
		this.pageTitle = pageTitle;
		this.pageTitleEn = pageTitleEn;
		this.pageContent = pageContent;
		this.pageContentEn = pageContentEn;
		this.pageHtml = pageHtml;
		this.pageHtmlEn = pageHtmlEn;
		this.pageSeo = pageSeo;
		this.pageGa = pageGa;
		this.pageFb = pageFb;
		this.pageHit = pageHit;
		this.status = status;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.systemMemo = systemMemo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "page_name", length = 50)
	public String getPageName() {
		return this.pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	@Column(name = "page_name_en", length = 50)
	public String getPageNameEn() {
		return this.pageNameEn;
	}

	public void setPageNameEn(String pageNameEn) {
		this.pageNameEn = pageNameEn;
	}

	@Column(name = "page_url", length = 150)
	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	@Column(name = "page_type", length = 10)
	public String getPageType() {
		return this.pageType;
	}

	public void setPageType(String pageType) {
		this.pageType = pageType;
	}

	@Column(name = "page_title", length = 60)
	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

	@Column(name = "page_title_en", length = 60)
	public String getPageTitleEn() {
		return this.pageTitleEn;
	}

	public void setPageTitleEn(String pageTitleEn) {
		this.pageTitleEn = pageTitleEn;
	}

	@Column(name = "page_content")
	public String getPageContent() {
		return this.pageContent;
	}

	public void setPageContent(String pageContent) {
		this.pageContent = pageContent;
	}

	@Column(name = "page_content_en")
	public String getPageContentEn() {
		return this.pageContentEn;
	}

	public void setPageContentEn(String pageContentEn) {
		this.pageContentEn = pageContentEn;
	}

	@Column(name = "page_html")
	public String getPageHtml() {
		return this.pageHtml;
	}

	public void setPageHtml(String pageHtml) {
		this.pageHtml = pageHtml;
	}

	@Column(name = "page_html_en")
	public String getPageHtmlEn() {
		return this.pageHtmlEn;
	}

	public void setPageHtmlEn(String pageHtmlEn) {
		this.pageHtmlEn = pageHtmlEn;
	}

	@Column(name = "page_seo", length = 150)
	public String getPageSeo() {
		return this.pageSeo;
	}

	public void setPageSeo(String pageSeo) {
		this.pageSeo = pageSeo;
	}

	@Column(name = "page_ga", length = 150)
	public String getPageGa() {
		return this.pageGa;
	}

	public void setPageGa(String pageGa) {
		this.pageGa = pageGa;
	}

	@Column(name = "page_fb", length = 150)
	public String getPageFb() {
		return this.pageFb;
	}

	public void setPageFb(String pageFb) {
		this.pageFb = pageFb;
	}

	@Column(name = "page_hit", length = 10)
	public String getPageHit() {
		return this.pageHit;
	}

	public void setPageHit(String pageHit) {
		this.pageHit = pageHit;
	}

	@Column(name = "status",  length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
