package tw.com.ezlifetech.ezReco.model;
// Generated 2019/6/22 �U�� 10:57:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import tw.com.ezlifetech.ezReco.common.model.GenericEntity;

/**
 * WorkClassShiftDl generated by hbm2java
 */
@Entity
@Table(name = "work_class_shift_dl", schema = "public")
public class WorkClassShiftDl extends GenericEntity<String> {

	private String id;
	private String htId;
	private String isMain;
	private String className;
	private String contractType;
	private String remuneration;
	private String sdateTime;
	private String edateTime;
	private String salary;
	private String extendIn;
	private String extendOut;
	private String nightAdd;
	private String kpi;
	private String unit;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String systemMemo;

	public WorkClassShiftDl() {
	}

	public WorkClassShiftDl(String id, String htId, String isMain, String createUser, Date createTime) {
		this.id = id;
		this.htId = htId;
		this.isMain = isMain;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ht_id", nullable = false, length = 30)
	public String getHtId() {
		return this.htId;
	}

	public void setHtId(String htId) {
		this.htId = htId;
	}

	@Column(name = "is_main", nullable = false, length = 5)
	public String getIsMain() {
		return this.isMain;
	}

	public void setIsMain(String isMain) {
		this.isMain = isMain;
	}

	@Column(name = "class_name", length = 200)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "contract_type", length = 30)
	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	

	@Column(name = "remuneration", length = 30)
	public String getRemuneration() {
		return this.remuneration;
	}

	public void setRemuneration(String remuneration) {
		this.remuneration = remuneration;
	}

	@Column(name = "sdate_time", length = 10)
	public String getSdateTime() {
		return this.sdateTime;
	}

	public void setSdateTime(String sdateTime) {
		this.sdateTime = sdateTime;
	}

	@Column(name = "edate_time", length = 10)
	public String getEdateTime() {
		return this.edateTime;
	}

	public void setEdateTime(String edateTime) {
		this.edateTime = edateTime;
	}

	@Column(name = "salary", length = 30)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "extend_in", length = 30)
	public String getExtendIn() {
		return this.extendIn;
	}

	public void setExtendIn(String extendIn) {
		this.extendIn = extendIn;
	}

	@Column(name = "extend_out", length = 30)
	public String getExtendOut() {
		return this.extendOut;
	}

	public void setExtendOut(String extendOut) {
		this.extendOut = extendOut;
	}

	@Column(name = "night_add", length = 30)
	public String getNightAdd() {
		return this.nightAdd;
	}

	public void setNightAdd(String nightAdd) {
		this.nightAdd = nightAdd;
	}

	@Column(name = "kpi", length = 30)
	public String getKpi() {
		return this.kpi;
	}

	public void setKpi(String kpi) {
		this.kpi = kpi;
	}

	@Column(name = "unit", length = 30)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "create_user", nullable = false, length = 30)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 29)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_user", length = 30)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 29)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "system_memo", length = 100)
	public String getSystemMemo() {
		return this.systemMemo;
	}

	public void setSystemMemo(String systemMemo) {
		this.systemMemo = systemMemo;
	}

}
